const { chromium } = require('../tools/commerce-analysis/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  await page.request.put('http://127.0.0.1:3129/api/mcp/settings',{data:{servers:[]}});
  const errors=[];
  page.on('pageerror', e => {if(e.stack?.includes('mcp-settings'))errors.push(e.message);});
  await page.goto('http://127.0.0.1:3129/');
  await page.evaluate(() => {localStorage.setItem('studio_active_page','canvas');});
  await page.getByRole('button',{name:'MCP 设置',exact:true}).click();
  await page.getByRole('button',{name:'＋ 添加',exact:true}).click();
  await page.locator('#mcp-name').fill('Blender 测试');
  await page.locator('#mcp-command').fill('python');
  await page.locator('#mcp-args').fill('["服务.py"]');
  await page.locator('#mcp-enabled').uncheck();
  await page.locator('#mcp-save').click();
  await page.getByText('设置已保存',{exact:true}).waitFor();
  await page.locator('#mcp-close').click();
  await page.getByRole('button',{name:'MCP 设置',exact:true}).click();
  await page.locator('#mcp-name').waitFor();
  await page.waitForFunction(()=>!document.getElementById('mcp-save').disabled);
  assert.equal(await page.locator('#mcp-name').inputValue(),'Blender 测试');
  assert.equal(await page.locator('#mcp-enabled').isChecked(),false);
  await page.locator('#mcp-file').setInputFiles({name:'servers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({mcpServers:{Photoshop:{command:'npx',args:['-y','example-mcp']}}}))});
  console.log('Import status:',await page.locator('#mcp-status').textContent());
  await page.getByText('已导入 1 个服务，请检查后保存。',{exact:true}).waitFor();
  await page.locator('#mcp-args').fill('invalid');
  await page.locator('#mcp-save').click();
  await page.getByText('启动参数不是有效 JSON',{exact:true}).waitFor();
  await page.locator('#mcp-args').fill('[]');
  await page.locator('#mcp-command').fill('xiaomei-no-such-command');
  await page.locator('#mcp-test').click();
  await page.getByText('连接失败，请检查启动命令、参数、工作目录或服务地址及鉴权配置。',{exact:true}).waitFor();
  await page.locator('#mcp-command').fill('npx');
  await page.screenshot({path:'C:/Users/小美/Documents/临时对话/mcp-settings-desktop.png'});
  await page.setViewportSize({width:600,height:800});
  assert.equal(await page.locator('#mcp-modal').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.screenshot({path:'C:/Users/小美/Documents/临时对话/mcp-settings-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('MCP UI: persistence, toggle, import, invalid JSON, failed connection, responsive layout passed');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
